from __future__ import annotations

from .attention_corpus_models import AttentionScenario


SCENARIOS_B: tuple[AttentionScenario, ...] = (
    AttentionScenario(
        "Technology & AI",
        "Deadline",
        "WWDC posture change",
        "WWDC",
        (
            "WWDC keynote is tomorrow; three project assumptions may change",
            "WWDC happened; three iOS changes matter to Mike's projects",
            "WWDC follow-up window closes before the weekend",
        ),
        (
            "The event is not Apple news; it is the chance to update project assumptions.",
            "This belongs when the keynote changes what Mike would build or postpone.",
        ),
        "Mike needs a practical summary of what changed for his own apps.",
        "He can update project direction before stale assumptions harden.",
        "He misses a short window to adjust active iOS work.",
        ("Apple developer news", "WWDC", "project notes"),
        True,
        ("keynote date", "developer impact", "project assumptions"),
    ),
    AttentionScenario(
        "Technology & AI",
        "Monitoring",
        "model pricing posture",
        "AI pricing",
        (
            "AI pricing shifted but does not change Mike's default yet",
            "Model cost moved enough to keep side-project economics on watch",
            "Pricing change is real but still below the workflow threshold",
        ),
        (
            "Pricing is only useful when it changes project economics or tool defaults.",
            "The item should mostly stay quiet until there is a practical threshold crossing.",
        ),
        "Mike cares about cost when it affects what he can ship.",
        "He can avoid reacting to every pricing page change.",
        "Generic AI pricing news eats attention without changing behavior.",
        ("pricing page", "usage spend", "side-project plan"),
    ),
    AttentionScenario(
        "Personal & Family",
        "Deadline",
        "family date",
        "family calendar",
        (
            "{family_event} is inside {days} days",
            "{family_event} needs a gift or plan before the week fills up",
            "Family commitment moved from background to calendar risk",
        ),
        (
            "This restores personal context before work absorbs the day.",
            "The event belongs here because the cost of forgetting is social, not technical.",
        ),
        "Mike wants the system to remember the human calendar he would otherwise drop.",
        "A small early action prevents an avoidable scramble.",
        "The date is forgotten until it becomes awkward.",
        ("calendar", "notes", "messages"),
        True,
    ),
    AttentionScenario(
        "Dog",
        "Maintenance",
        "Bogey care schedule",
        "Bogey",
        (
            "Bogey's heartworm refill is due in {days} days",
            "Bogey grooming is overdue by {days} days",
            "Annual vet visit window opened for Bogey",
        ),
        (
            "Dog care is exactly the kind of real-life obligation the system should preserve.",
            "This is not a pet category; it is a concrete care object with expiration.",
        ),
        "Bogey belongs in the model because Mike cares and the tasks are easy to forget.",
        "The system can surface care windows before they become urgent.",
        "A small recurring obligation becomes stress or risk.",
        ("calendar", "vet email", "notes"),
    ),
    AttentionScenario(
        "Dog",
        "Deadline",
        "Bogey trip coverage",
        "Bogey boarding",
        (
            "Bogey boarding is not booked for the trip in {days} days",
            "Dog-care coverage is the open item for vacation",
            "Trip logistics depend on confirming Bogey coverage",
        ),
        (
            "This deserves attention when it blocks travel confidence.",
            "The system should catch pet logistics before they collide with departure.",
        ),
        "Dog logistics are part of the real plan, not a side note.",
        "Mike can close the loop while there are still options.",
        "Travel gets expensive or stressful at the last minute.",
        ("calendar", "boarding email", "travel notes"),
        True,
    ),
    AttentionScenario(
        "Sports & Golf",
        "Monitoring",
        "sports context",
        "Yankees and Rutgers",
        (
            "Yankees result changed nothing; standings context stays quiet",
            "Rutgers kickoff window matters only if travel logistics change",
            "Major championship weekend is watchable, but not attention-worthy yet",
        ),
        (
            "Sports should stay suppressed unless it changes planning or real context.",
            "The value is not a score; it is whether Mike's weekend or season posture changed.",
        ),
        "Mike follows sports, but routine results should not steal the briefing.",
        "The system proves it can suppress familiar low-value updates.",
        "The product drifts into a sports dashboard.",
        ("sports schedule", "team news", "ticket portal"),
    ),
    AttentionScenario(
        "Sports & Golf",
        "Noise",
        "routine score",
        "routine sports result",
        (
            "Yankees won a routine June game",
            "Rutgers offseason note has no planning effect",
            "Golf leaderboard moved, but Mike has no reason to act",
        ),
        (
            "This is intentionally present so the corpus proves routine sports can be ignored.",
            "A personal operating system should know Mike likes sports and still suppress low-value results.",
        ),
        "Sports interest is real, but routine scores should not become morning attention.",
        "The system protects the briefing from turning into a scoreboard.",
        "The product drifts into generic sports content.",
        ("sports schedule", "team news", "leaderboard"),
    ),
    AttentionScenario(
        "Golf Equipment",
        "Opportunity",
        "club setup",
        "golf equipment",
        (
            "Ping release creates a G430 replacement question",
            "Club fitting slot opened during Mike's range window",
            "Range pass renewal is inside {days} days",
        ),
        (
            "Golf equipment gets attention when it intersects timing, fit, or a real buying window.",
            "This is a specific Mike interest that generic personal categories miss.",
        ),
        "Mike spends enough attention here that the corpus should model it directly.",
        "He can catch useful fitting or renewal windows without browsing.",
        "A real hobby window is missed while generic sports items fill the corpus.",
        ("golf shop email", "manufacturer release", "range account"),
        True,
    ),
    AttentionScenario(
        "Books & Entertainment",
        "Monitoring",
        "media queue",
        "books and shows",
        (
            "{show_or_book} released, but no action is needed today",
            "Series finale is available after prior watch",
            "Book recommendation matches Mike's prior queue",
        ),
        (
            "Entertainment should exist in the world model while usually staying suppressed.",
            "It can be useful when it connects to prior watching or reading intent.",
        ),
        "Mike's actual life includes media and recommendations, not just work and markets.",
        "The system can preserve light personal context without over-promoting it.",
        "The corpus becomes too narrow and utilitarian to feel personal.",
        ("streaming queue", "book notes", "recommendation"),
    ),
    AttentionScenario(
        "Books & Entertainment",
        "Noise",
        "generic media release",
        "entertainment noise",
        (
            "Generic streaming release has no prior-watch hook",
            "Book list update does not match Mike's queue",
            "Trailer drop is interesting but not attention-worthy",
        ),
        (
            "The category exists, but most entertainment inputs should be suppressed.",
            "This prevents the corpus from confusing personal texture with required attention.",
        ),
        "Mike's interests should exist without creating fake obligations.",
        "The briefing remains personal without becoming a media feed.",
        "Low-value entertainment updates crowd out real context.",
        ("streaming feed", "book list", "recommendation"),
    ),
    AttentionScenario(
        "Health",
        "Maintenance",
        "basic health admin",
        "health logistics",
        (
            "Prescription refill window opens in {days} days",
            "Annual physical scheduling window is open",
            "Eye exam is due this month",
        ),
        (
            "This avoids medical interpretation and focuses on ordinary logistics.",
            "The event matters because it is easy to defer until appointments become harder.",
        ),
        "Health logistics are real attention objects without becoming medical advice.",
        "Mike can schedule routine care before it becomes annoying.",
        "Basic admin gets deferred until options narrow.",
        ("calendar", "pharmacy notice", "provider portal"),
    ),
    AttentionScenario(
        "Life Logistics",
        "Deadline",
        "civilian paperwork",
        "life logistics",
        (
            "Passport expires inside {days} days",
            "TSA PreCheck renewal window opened",
            "Car registration renewal is inside {days} days",
        ),
        (
            "These are the exact forgotten obligations that justify a personal operating system.",
            "The object is a real-world expiration with avoidable friction.",
        ),
        "Mike should not have to remember every low-frequency administrative deadline.",
        "A small timely action prevents future travel or paperwork friction.",
        "An avoidable expiration becomes a painful errand.",
        ("email", "calendar", "state portal"),
        True,
    ),
    AttentionScenario(
        "Life Logistics",
        "Maintenance",
        "household finance date",
        "property taxes",
        (
            "Property taxes are due inside {days} days",
            "Insurance document needs renewal before the mortgage file update",
            "Life-admin deadline is close enough to leave monitoring",
        ),
        (
            "Life logistics matter because forgetting them creates real cost.",
            "This should surface only when date pressure exists.",
        ),
        "The model needs mundane but consequential paperwork.",
        "Mike can handle it before it becomes a weekend tax.",
        "The missed item creates fee, friction, or stress.",
        ("email", "calendar", "home folder"),
        True,
    ),
    AttentionScenario(
        "Home Ownership",
        "Maintenance",
        "home maintenance",
        "home upkeep",
        (
            "HVAC service window is filling before the heat stretch",
            "Air filters are overdue by {days} days",
            "Dryer vent cleaning has been deferred twice",
        ),
        (
            "This is the right kind of maintenance: boring until ignored.",
            "It should appear when timing or risk turns a small chore into leverage.",
        ),
        "Home upkeep should be caught before it becomes a larger problem.",
        "Small maintenance prevents bigger cost or stress.",
        "The house accumulates avoidable deferred work.",
        ("home checklist", "calendar", "seasonal rule"),
    ),
    AttentionScenario(
        "Travel",
        "Deadline",
        "trip departure",
        "travel logistics",
        (
            "Flight departure is inside {days} days and parking is not confirmed",
            "Vacation weather changed the packing plan",
            "Return logistics are still open before departure",
        ),
        (
            "Travel attention should restore the specific open loop before the trip arrives.",
            "Destination content is noise; missing logistics are the event.",
        ),
        "Mike needs travel open loops surfaced before they become expensive.",
        "He can close parking, packing, or return details while there is time.",
        "Travel mistakes are costly to recover from.",
        ("calendar", "airline email", "weather"),
        True,
        ("flight", "weather", "parking", "return plan"),
    ),
    AttentionScenario(
        "Side Projects",
        "Context Change",
        "ship-or-stop decision",
        "side-project direction",
        (
            "Side project has gone {days} days without a user-facing step",
            "Validation evidence changed the ship-or-stop decision",
            "Infrastructure spend rose without product progress",
        ),
        (
            "The item matters when it changes whether Mike should keep investing attention.",
            "This should avoid task churn and focus on project posture.",
        ),
        "Mike wants side projects judged by momentum and fit, not backlog size.",
        "He can stop, ship, or narrow the next step with better context.",
        "A project becomes a quiet time sink.",
        ("GitHub", "billing email", "project notes"),
        True,
    ),
    AttentionScenario(
        "Watch Items",
        "Monitoring",
        "object plus conditions",
        "user-created watch",
        (
            "{watch_object} has no meaningful change yet",
            "{watch_object} condition changed enough to mention",
            "{watch_object} expires in {days} days",
        ),
        (
            "A watch is an object with conditions and expiration, not content to read.",
            "The correct default is silence until timing, threshold, or conditions change.",
        ),
        "Mike should not need to remember to re-check active watch objects.",
        "The system can surface only the watches that changed.",
        "Mike has to manually poll objects he already told the system about.",
        ("user-created watch", "calendar", "weather", "market threshold"),
        False,
        ("condition changed", "decision window", "expiration"),
    ),
)
