from __future__ import annotations

from .attention_corpus_models import ConfiguredWatch, WatchPreset

CONFIGURED_WATCHES: tuple[ConfiguredWatch, ...] = (
    ConfiguredWatch(
        "Outdoor concert Friday",
        "outdoor concert",
        ("weather", "parking prices", "venue policy", "timing"),
        ("calendar", "weather", "venue email", "parking feed"),
        "daily until 72 hours out, then morning and afternoon",
        (
            "rain risk > 35%",
            "parking changes materially",
            "event is within 48 hours",
            "venue sends an update",
        ),
        (
            "generic reminders",
            "unchanged weather",
            "concert is coming up filler",
        ),
        "day after event",
        "brief only what changed or what needs a decision",
    ),
    ConfiguredWatch(
        "Bitcoin range",
        "Bitcoin",
        ("price range", "liquidity", "macro risk", "cash availability"),
        ("CoinGecko", "market close", "portfolio import"),
        "daily after market close",
        ("configured accumulation range crossed", "weekly move changes risk posture"),
        ("minor daily moves", "generic crypto headlines", "price-only updates"),
        "until range is retired",
        "decision-window note",
    ),
    ConfiguredWatch(
        "UNH watch",
        "UNH",
        ("drawdown", "healthcare sector context", "portfolio exposure"),
        ("portfolio import", "market close", "sector watch"),
        "daily after market close",
        ("drawdown materially changes assumptions", "sector weakness accelerates"),
        ("routine price noise", "generic analyst notes"),
        "until watch thesis is closed",
        "context change note",
    ),
    ConfiguredWatch(
        "Market backdrop",
        "S&P breadth, AI trade, oil, and Fed path",
        ("S&P breadth", "QQQ concentration", "AI stocks", "oil", "Fed path"),
        ("market close", "index breadth", "sector watch", "Fed calendar"),
        "daily after market close, plus after macro events",
        ("risk backdrop changes", "breadth diverges from index", "macro path changes"),
        ("minor index moves", "generic market commentary", "price-only updates"),
        "until backdrop watch is retired",
        "context change note",
    ),
    ConfiguredWatch(
        "Mortgage rates",
        "mortgage-rate watch",
        ("rate threshold", "Fed signal", "housing inventory"),
        ("FRED", "mortgage rate feed", "housing watch"),
        "weekly, plus after Fed/CPI events",
        ("rate threshold crossed", "housing math changes materially"),
        ("unchanged rates", "generic housing news"),
        "configured review window",
        "decision-window note",
    ),
    ConfiguredWatch(
        "Bogey care",
        "Bogey",
        ("vet schedule", "heartworm refill", "grooming", "boarding"),
        ("calendar", "vet email", "notes", "boarding email"),
        "weekly, daily inside travel windows",
        ("care deadline inside 7 days", "boarding missing before travel"),
        ("generic pet reminders", "completed care items"),
        "after care window closes",
        "small action reminder",
    ),
    ConfiguredWatch(
        "Travel logistics",
        "trip logistics",
        ("flight", "parking", "weather", "packing", "return plan"),
        ("calendar", "airline email", "weather", "travel advisory"),
        "daily inside 7 days",
        ("departure is near", "parking missing", "weather changes packing or timing"),
        ("generic countdowns", "unchanged itinerary", "destination filler"),
        "return date",
        "open travel loop",
    ),
    ConfiguredWatch(
        "Yankees and Rutgers",
        "Yankees/Rutgers season and ticket posture",
        ("standings context", "ticket deadlines", "kickoff logistics"),
        ("sports schedule", "team news", "ticket portal"),
        "daily in season",
        ("planning or standings context changes", "ticket deadline nears"),
        ("routine wins", "routine losses", "generic offseason notes"),
        "end of season or renewal window",
        "only planning/context changes",
    ),
    ConfiguredWatch(
        "Golf weather and equipment",
        "golf setup",
        ("weather window", "tee time", "equipment release", "fitting slots"),
        ("weather", "course email", "manufacturer release", "range account"),
        "weekly, plus day before tee times",
        ("playability changes", "fitting slot opens", "renewal window nears"),
        ("generic golf content", "unchanged forecasts"),
        "after tee time or renewal window",
        "planning or opportunity note",
    ),
    ConfiguredWatch(
        "Work migrations",
        "work migration posture",
        ("adoption count", "team response gap", "deadline", "blast radius"),
        ("GitHub Enterprise", "Slack", "Jira", "security tooling"),
        "workday mornings",
        ("deadline or response gap threatens plan", "exposure count changes"),
        ("project-name updates", "unchanged status", "generic rollout chatter"),
        "after migration freeze",
        "posture change or escalation note",
    ),
    ConfiguredWatch(
        "Side projects",
        "side-project direction",
        ("shipping momentum", "validation evidence", "cost", "expiration"),
        ("GitHub", "billing email", "project notes", "domain registrar"),
        "twice weekly",
        ("ship-or-stop posture changes", "cost rises without progress"),
        ("task backlog churn", "generic repo activity"),
        "after project is shipped, stopped, or archived",
        "ship-or-stop note",
    ),
    ConfiguredWatch(
        "Home maintenance",
        "home upkeep",
        ("service windows", "seasonal risk", "deferred tasks", "renewals"),
        ("home checklist", "calendar", "email", "seasonal rule"),
        "weekly",
        ("due inside 10 days", "deferred repeatedly", "season changes risk"),
        ("generic home tips", "not-due-yet chores"),
        "after task is completed or season passes",
        "small action reminder",
    ),
    ConfiguredWatch(
        "Life logistics",
        "administrative deadlines",
        ("passport", "TSA PreCheck", "car registration", "property taxes"),
        ("email", "calendar", "state portal", "home folder"),
        "weekly, daily inside due windows",
        ("expiration or due date is inside action window", "paperwork blocks travel"),
        ("generic reminders", "paperwork with no open loop"),
        "after deadline is closed",
        "small action reminder",
    ),
    ConfiguredWatch(
        "Family dates",
        "family calendar",
        ("birthdays", "holidays", "gift windows", "visit logistics"),
        ("calendar", "notes", "messages"),
        "weekly, daily inside 7 days",
        ("date inside 7 days", "gift or plan not closed"),
        ("generic calendar reminders", "events with no open loop"),
        "day after event",
        "small action reminder",
    ),
    ConfiguredWatch(
        "WWDC and coding tools",
        "developer tooling posture",
        ("workflow friction", "developer impact", "pricing", "project assumptions"),
        ("vendor changelog", "developer docs", "project notes", "pricing page"),
        "daily during event windows, otherwise weekly",
        ("tool default should change", "project assumption changes", "cost model changes"),
        ("generic launch coverage", "unchanged benchmarks", "rumor recap"),
        "after event window or tool trial closes",
        "posture change note",
    ),
    ConfiguredWatch(
        "Health admin",
        "health logistics",
        ("refill window", "annual physical", "eye exam", "appointment availability"),
        ("calendar", "pharmacy notice", "provider portal"),
        "monthly, weekly inside due windows",
        ("routine care window opens", "appointment slots narrow", "refill gap nears"),
        ("medical interpretation", "generic wellness content", "not-due-yet reminders"),
        "after appointment or refill is closed",
        "small action reminder",
    ),
    ConfiguredWatch(
        "Media queue",
        "books and shows",
        ("prior-watch hook", "saved recommendation", "release timing"),
        ("streaming queue", "book notes", "recommendation"),
        "weekly",
        ("prior intent matches release", "recommendation fits saved queue"),
        ("generic releases", "trailer drops", "lists with no prior intent"),
        "after queue item is watched, read, or ignored",
        "light personal context note",
    ),
)

WATCH_PRESETS: tuple[WatchPreset, ...] = (
    WatchPreset(
        "Markets",
        "Bitcoin range",
        ("market close", "crypto feed", "portfolio import"),
        "daily after market close",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Sports teams",
        "Yankees and Rutgers",
        ("sports schedule", "team news", "ticket portal"),
        "daily in season",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Travel",
        "Outdoor concert Friday",
        ("calendar", "weather", "venue email", "travel email"),
        "daily inside 7 days",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Family dates",
        "Family dates",
        ("calendar", "notes", "messages"),
        "weekly, daily inside 7 days",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Home maintenance",
        "Home maintenance",
        ("home checklist", "calendar", "email"),
        "weekly",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Pets",
        "Bogey care",
        ("calendar", "vet email", "notes"),
        "weekly, daily inside travel windows",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Medical appointments",
        "Health admin",
        ("calendar", "pharmacy notice", "provider portal"),
        "monthly, weekly inside due windows",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Work projects",
        "Work migrations",
        ("GitHub Enterprise", "Slack", "Jira"),
        "workday mornings",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Side projects",
        "Side projects",
        ("GitHub", "billing email", "project notes"),
        "twice weekly",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
    WatchPreset(
        "Tech interests",
        "WWDC and coding tools",
        ("vendor changelog", "developer docs", "project notes"),
        "daily during event windows, otherwise weekly",
        ("object", "conditions", "sources", "cadence", "surface_rules", "suppression_rules", "expiration", "preferred_output"),
    ),
)


