from __future__ import annotations

from .attention_corpus_models import AttentionScenario


SCENARIOS_A: tuple[AttentionScenario, ...] = (
    AttentionScenario(
        "Work",
        "Deadline",
        "namespace migration adoption",
        "namespace migration",
        (
            "{repos} repos still not migrated before namespace freeze",
            "{teams} teams have not answered the namespace migration ask",
            "Namespace adoption stalled at {percent}% with freeze inside {days} days",
        ),
        (
            "This is not a project update; it is the unresolved adoption count Mike would need before the next escalation path closes.",
            "The useful fact is who is still exposed and whether silence has become the problem.",
        ),
        "Mike owns the posture of the migration, not the label of the migration project.",
        "A small nudge can unblock teams before the deadline becomes an executive problem.",
        "Late migration creates coordination churn and avoidable escalation.",
        ("GitHub Enterprise", "Slack", "migration tracker"),
        True,
    ),
    AttentionScenario(
        "Work",
        "Deadline",
        "executive decision packet",
        "executive deck",
        (
            "Executive deck due {weekday}; adoption story is still missing",
            "Tuesday deck needs the risk narrative before review",
            "Leadership review moved up with {days} days to reconcile metrics",
        ),
        (
            "The deck matters only because it compresses several workstreams into one decision surface.",
            "This belongs in the briefing when the narrative is the blocker, not when slides merely exist.",
        ),
        "Mike needs the decision-ready version before work fragments the day.",
        "Catching it early preserves time to turn scattered status into a clear ask.",
        "The meeting can turn into follow-up churn instead of a decision.",
        ("calendar", "slides", "Slack"),
        True,
    ),
    AttentionScenario(
        "Work",
        "Context Change",
        "security exposure count",
        "critical KEV exposure",
        (
            "Critical KEV now maps to {services} services",
            "{services} services inherited the new KEV exposure",
            "KEV blast radius grew after dependency inventory refresh",
        ),
        (
            "The important event is the change in blast radius, not a scanner headline.",
            "This changes where Mike should expect security attention to land today.",
        ),
        "Security work becomes real when the exposure maps to owned services.",
        "Mike can separate true escalation risk from generic vulnerability noise.",
        "The day starts with stale risk assumptions.",
        ("security tooling", "service inventory", "GitHub"),
        True,
    ),
    AttentionScenario(
        "Work",
        "Monitoring",
        "platform adoption",
        "Sonar onboarding",
        (
            "Sonar onboarding is at {percent}% of target",
            "{teams} teams still missing Sonar onboarding evidence",
            "Sonar coverage moved, but not enough to change posture",
        ),
        (
            "This should usually stay in monitoring until the gap threatens a review.",
            "The briefing should carry the adoption gap, not a generic rollout name.",
        ),
        "The attention object is coverage against a target.",
        "Mike knows whether to leave it quiet or ask for a status reset.",
        "A stalled adoption curve can hide until the review window is already closed.",
        ("Sonar", "Jira", "Slack"),
    ),
    AttentionScenario(
        "Work",
        "Context Change",
        "duplicate method cluster",
        "namespace code duplication",
        (
            "One namespace has {duplicates} duplicate methods",
            "Duplicate-method cluster is now concentrated in one namespace",
            "{duplicates} duplicate methods point to a consolidation candidate",
        ),
        (
            "This matters because it converts vague cleanup into one concrete attention object.",
            "It is worth mention when the code shape reveals leverage, not when a report is merely long.",
        ),
        "Mike responds to leverage points more than generic tech debt.",
        "A focused cleanup target can replace scattered low-value review.",
        "The useful consolidation opportunity remains hidden in raw reports.",
        ("static analysis", "repository scan", "GitHub"),
    ),
    AttentionScenario(
        "Work",
        "Monitoring",
        "team response gap",
        "team adoption silence",
        (
            "{teams} teams have not responded after the second reminder",
            "Adoption silence is now the blocker, not tooling",
            "Response gap grew while the deadline stayed fixed",
        ),
        (
            "The event is a social coordination gap that can become a delivery risk.",
            "This is not a status update; it identifies the part Mike may need to unblock.",
        ),
        "Mike needs to know when silence, not engineering, is the problem.",
        "A targeted follow-up can prevent a late surprise.",
        "No one notices the absence of response until there is no time left.",
        ("Slack", "email", "Jira"),
    ),
    AttentionScenario(
        "Work",
        "Context Change",
        "repo consolidation velocity",
        "repo consolidation",
        (
            "Repo consolidation slowed to {repos} merges this week",
            "Consolidation velocity fell below the adoption plan",
            "{repos} repos moved, but the long tail is no longer shrinking",
        ),
        (
            "The meaningful signal is whether the long tail is shrinking fast enough.",
            "A project name is irrelevant; the count and trajectory are the attention object.",
        ),
        "Mike cares whether the effort is still converting into fewer things to own.",
        "The briefing can distinguish temporary noise from a stuck consolidation plan.",
        "A slowed long tail becomes permanent maintenance cost.",
        ("GitHub", "migration tracker", "calendar"),
    ),
    AttentionScenario(
        "Finance & Markets",
        "Monitoring",
        "Bitcoin decision range",
        "Bitcoin",
        (
            "Bitcoin is {pct}% from Mike's accumulation range",
            "Bitcoin moved {pct}% this week but still has no decision hook",
            "Bitcoin pullback is close enough to keep quiet watch active",
        ),
        (
            "Bitcoin belongs in the corpus because it shapes Mike's world model even when no trade is implied.",
            "Most Bitcoin moves should die as monitoring unless the range actually matters.",
        ),
        "Mike tracks Bitcoin for context and optionality, not because every move deserves action.",
        "The system can monitor the range without forcing a portfolio decision.",
        "Mike goes back to checking market apps manually.",
        ("CoinGecko", "market close", "portfolio import"),
        True,
    ),
    AttentionScenario(
        "Finance & Markets",
        "Context Change",
        "market breadth",
        "S&P breadth",
        (
            "S&P breadth improved to {percent}% above the 50-day average",
            "SPY is flat, but breadth finally improved",
            "Market breadth no longer matches the index headline",
        ),
        (
            "The value is the change in market structure, not a raw index price.",
            "This gives Mike context for risk appetite without pretending to be advice.",
        ),
        "Mike follows the market backdrop as part of his model of the world.",
        "He can understand whether index strength is broadening or still narrow.",
        "The headline index move hides the real market posture.",
        ("market close", "index breadth", "finance topic"),
    ),
    AttentionScenario(
        "Finance & Markets",
        "Monitoring",
        "AI stock risk appetite",
        "AI infrastructure stocks",
        (
            "AI infrastructure stocks pulled back {pct}% from highs",
            "AI trade cooled while QQQ held its range",
            "AI-stock pullback is notable, but not a decision by itself",
        ),
        (
            "This belongs as world-model context, not as a trading prompt.",
            "The system should mention it only when it changes the risk backdrop.",
        ),
        "Mike pays attention to AI market temperature because it affects broader tech sentiment.",
        "He gets context without needing to scan tickers.",
        "The briefing misses a major shift in the tech risk backdrop.",
        ("market close", "QQQ", "sector watch"),
    ),
    AttentionScenario(
        "Finance & Markets",
        "Context Change",
        "healthcare holding risk",
        "UNH",
        (
            "UNH is down another {pct}% while healthcare lag widens",
            "UNH drawdown changed the portfolio context again",
            "UNH weakness is now large enough to re-check assumptions",
        ),
        (
            "This is relevant when it changes the story around a watched name.",
            "It should not become a generic holdings card.",
        ),
        "Mike follows UNH as a specific watched object in the market map.",
        "He can notice when the move becomes context, not just price noise.",
        "A meaningful holding-specific shift blends into daily market clutter.",
        ("portfolio import", "market close", "watch range"),
        True,
    ),
    AttentionScenario(
        "Finance & Markets",
        "Opportunity",
        "mortgage rate threshold",
        "mortgage rates",
        (
            "Mortgage rates moved back below {rate}%",
            "Mortgage-rate watch crossed Mike's review threshold",
            "Rate drop changes the housing math for the first time this month",
        ),
        (
            "This matters because it can change housing or cash posture, not because rates changed in isolation.",
            "A rate threshold is exactly the kind of object that should stay quiet until crossed.",
        ),
        "Mike tracks rates because they can change a real-life decision window.",
        "The system can surface a rare decision window instead of daily rate noise.",
        "A useful housing window may pass unnoticed.",
        ("FRED", "mortgage rate feed", "housing watch"),
        True,
    ),
    AttentionScenario(
        "Finance & Markets",
        "Context Change",
        "macro inflation path",
        "Fed and CPI path",
        (
            "Fed path shifted after CPI cooled to {pct}%",
            "CPI changed the expected rate path, not just the news cycle",
            "Labor data and CPI now point in different directions",
        ),
        (
            "The event is the posture change across rates, cash, and housing.",
            "This should be suppressed unless the macro picture changes Mike's assumptions.",
        ),
        "Mike follows macro because it changes how he interprets cash, stocks, and housing.",
        "He gets the practical posture change without reading generic Fed coverage.",
        "Macro headlines keep accumulating without a usable conclusion.",
        ("CPI calendar", "Fed calendar", "labor report"),
    ),
    AttentionScenario(
        "Finance & Markets",
        "Monitoring",
        "energy inflation pressure",
        "oil",
        (
            "Oil is up {pct}% this month",
            "Oil move is now large enough to affect inflation context",
            "Energy prices changed the macro backdrop but not a personal action",
        ),
        (
            "Oil belongs here as a world-model input, usually not a briefing lead.",
            "The system should distinguish macro context from personal urgency.",
        ),
        "Mike tracks oil as a macro pressure point.",
        "He can update context without being dragged into commodity news.",
        "A macro shift remains invisible until it shows up elsewhere.",
        ("market close", "energy market", "macro topic"),
    ),
    AttentionScenario(
        "Technology & AI",
        "Context Change",
        "coding-agent workflow",
        "Claude Code workflow",
        (
            "Claude Code now beats Mike's current workflow on test repair",
            "Coding-agent workflow crossed from interesting to usable",
            "Agent benchmark matters because it changes the default coding loop",
        ),
        (
            "The release is not the event; the event is whether Mike should change posture.",
            "This should suppress generic AI news and keep only practical workflow changes.",
        ),
        "Mike usually knows the release; he needs the posture change.",
        "He can decide whether the tool deserves more real work, not just curiosity.",
        "Tool defaults stay stale after capability has changed.",
        ("vendor changelog", "benchmark", "local workflow"),
        True,
    ),
    AttentionScenario(
        "Technology & AI",
        "Opportunity",
        "editor friction fix",
        "Cursor workflow",
        (
            "Cursor fixed the multi-file edit friction Mike keeps working around",
            "Cursor update finally removes a workflow tax",
            "Editor change matters because it fixes the exact loop Mike avoids",
        ),
        (
            "This is a tool posture event, not launch coverage.",
            "The item earns attention only if it changes how Mike would actually build.",
        ),
        "Mike cares when a tool removes recurring friction.",
        "Trying the update may save repeated project time.",
        "He keeps using a slower workflow out of habit.",
        ("release notes", "local workflow", "developer docs"),
        True,
    ),
)
