from __future__ import annotations

SLOT_BANKS = {
    "repos": [40, 37, 32, 28, 24, 19, 14, 11, 8, 5],
    "teams": [5, 4, 7, 3, 6, 2],
    "percent": [41, 48, 52, 57, 63, 68, 74, 79, 83],
    "days": [2, 3, 4, 5, 6, 7, 10, 14, 21, 29, 43, 61],
    "services": [12, 9, 16, 21, 7, 18],
    "duplicates": [87, 73, 64, 58, 49, 112],
    "pct": [3.4, 4.8, 6.1, 7.6, 8.0, 11.5, 15.0, 18.2],
    "rate": [5.9, 6.0, 6.1, 6.2],
    "weekday": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    "family_event": ["Father's Day", "nephew birthday", "family visit", "birthday dinner"],
    "show_or_book": [
        "The queued show",
        "The series finale",
        "The saved nonfiction recommendation",
        "The new season",
    ],
    "watch_object": [
        "WWDC",
        "outdoor concert",
        "vacation departure",
        "Rutgers renewal",
        "mortgage-rate watch",
        "Bitcoin range",
        "Bogey boarding",
        "golf trip weather",
    ],
}


TITLE_CONTEXTS = {
    "Work": [
        "after the second reminder",
        "before staff review",
        "with the freeze still fixed",
        "after the tracker refresh",
        "before the exec readout",
        "after owner silence",
        "with escalation risk rising",
        "before Friday status",
    ],
    "Finance & Markets": [
        "after market close",
        "before the Fed week",
        "with housing math in view",
        "after the weekly move",
        "before cash allocation review",
        "with breadth diverging",
        "after the CPI print",
        "with risk appetite cooling",
    ],
    "Technology & AI": [
        "after release notes landed",
        "before the next coding block",
        "after benchmark review",
        "with side projects in mind",
        "before tool defaults harden",
        "after WWDC follow-up",
        "with cost limits in view",
        "before workflow reset",
    ],
    "Dog": [
        "before the trip window",
        "after the calendar check",
        "before weekend errands",
        "with boarding options narrowing",
        "after the vet reminder",
        "before the refill gap",
    ],
    "Golf Equipment": [
        "before the fitting slots fill",
        "after the release note",
        "with range time planned",
        "before renewal pricing changes",
        "after the bag review",
        "with spring setup in mind",
    ],
    "Books & Entertainment": [
        "after queue refresh",
        "before weekend downtime",
        "with prior-watch context",
        "after recommendation review",
        "before it gets stale",
    ],
    "Health": [
        "before appointment slots narrow",
        "after provider reminder",
        "before refill gap",
        "with calendar space available",
        "after routine admin check",
    ],
    "Life Logistics": [
        "before paperwork friction",
        "after email scan",
        "with travel optionality in view",
        "before renewal window closes",
        "after calendar audit",
        "before weekend errands",
    ],
    "Home Ownership": [
        "before the heat stretch",
        "after seasonal checklist",
        "before service windows fill",
        "after deferral count changed",
        "with cost risk rising",
    ],
    "Travel": [
        "before departure week",
        "after weather refresh",
        "before parking fills",
        "with return plan still open",
        "after airline email",
    ],
    "Side Projects": [
        "after repo review",
        "before another build cycle",
        "with spend rising",
        "after validation notes",
        "before weekend coding time",
    ],
    "Watch Items": [
        "before expiration",
        "after condition check",
        "with no posture change",
        "as decision window nears",
        "after threshold review",
    ],
    "Personal & Family": [
        "before the week fills",
        "after calendar review",
        "before gift timing gets tight",
        "with work likely to crowd it out",
    ],
    "Sports & Golf": [
        "after scoreboard check",
        "before weekend plans",
        "with no standings change",
        "after ticket portal refresh",
    ],
}


SIMULATION_PATTERNS = [
    {"name": "quiet market and chores check", "dominant": None, "primary": None},
    {"name": "namespace adoption count becomes urgent", "dominant": "Work", "primary": "work", "subject": "namespace migration"},
    {"name": "mortgage rate threshold watch", "dominant": "Finance & Markets", "primary": "finance", "subject": "mortgage rates"},
    {"name": "trip parking and packing open loops", "dominant": "Travel", "primary": "travel", "subject": "travel logistics"},
    {"name": "deck deadline competes with family date", "dominant": "Work", "primary": "competing", "subject": "executive deck"},
    {"name": "routine sports and market noise", "dominant": None, "primary": None},
    {"name": "coding-agent workflow posture shift", "dominant": "Technology & AI", "primary": "technology", "subject": "Claude Code workflow"},
    {"name": "Bogey care window", "dominant": "Dog", "primary": "dog", "subject": "Bogey"},
    {"name": "property tax paperwork window", "dominant": "Life Logistics", "primary": "life", "subject": "property taxes"},
    {"name": "configured watch stays quiet", "dominant": None, "primary": None},
    {"name": "KEV blast radius widened", "dominant": "Work", "primary": "work", "subject": "critical KEV exposure"},
    {"name": "S&P breadth changed the backdrop", "dominant": "Finance & Markets", "primary": "finance", "subject": "S&P breadth"},
    {"name": "WWDC project assumptions changed", "dominant": "Technology & AI", "primary": "technology", "subject": "WWDC"},
    {"name": "home upkeep before weather shift", "dominant": "Home Ownership", "primary": "home", "subject": "home upkeep"},
    {"name": "side project ship-or-stop posture", "dominant": "Side Projects", "primary": "side-project", "subject": "side-project direction"},
    {"name": "nothing clears the attention bar", "dominant": None, "primary": None},
    {"name": "golf fitting window opened", "dominant": "Golf Equipment", "primary": "golf-equipment", "subject": "golf equipment"},
    {"name": "passport and travel paperwork", "dominant": "Life Logistics", "primary": "life", "subject": "life logistics"},
    {"name": "UNH drawdown changed context", "dominant": "Finance & Markets", "primary": "finance", "subject": "UNH"},
    {"name": "health admin scheduling window", "dominant": "Health", "primary": "health", "subject": "health logistics"},
    {"name": "team silence is the blocker", "dominant": "Work", "primary": "work", "subject": "team adoption silence"},
    {"name": "entertainment queue stays suppressed", "dominant": None, "primary": None},
    {"name": "club release but no same-day decision", "dominant": "Golf Equipment", "primary": "golf-equipment", "subject": "golf equipment"},
    {"name": "return travel detail still open", "dominant": "Travel", "primary": "travel", "subject": "travel logistics"},
    {"name": "macro data changed rate path", "dominant": "Finance & Markets", "primary": "finance", "subject": "Fed and CPI path"},
    {"name": "duplicate-method cluster is leverage", "dominant": "Work", "primary": "work", "subject": "namespace code duplication"},
    {"name": "AI pricing stays below threshold", "dominant": None, "primary": None},
    {"name": "Bogey trip coverage blocks confidence", "dominant": "Dog", "primary": "dog", "subject": "Bogey boarding"},
    {"name": "side-project cost without progress", "dominant": "Side Projects", "primary": "side-project", "subject": "side-project direction"},
    {"name": "home and family both need small actions", "dominant": "Personal & Family", "primary": "competing"},
    {"name": "oil move is only macro context", "dominant": None, "primary": None},
    {"name": "executive packet needs decision story", "dominant": "Work", "primary": "work", "subject": "executive deck"},
    {"name": "Bitcoin range nears but does not cross", "dominant": "Finance & Markets", "primary": None, "subject": "Bitcoin"},
    {"name": "Cursor removed recurring edit friction", "dominant": "Technology & AI", "primary": "technology", "subject": "Cursor workflow"},
    {"name": "car registration renewal surfaced", "dominant": "Life Logistics", "primary": "life", "subject": "life logistics"},
    {"name": "sports context stays low priority", "dominant": None, "primary": None},
    {"name": "travel weather changed packing", "dominant": "Travel", "primary": "travel", "subject": "travel logistics"},
    {"name": "annual physical scheduling window", "dominant": "Health", "primary": "health", "subject": "health logistics"},
    {"name": "repo consolidation long tail slowed", "dominant": "Work", "primary": "work", "subject": "repo consolidation"},
    {"name": "AI stocks pulled back but no action", "dominant": None, "primary": None},
    {"name": "family date has real timing risk", "dominant": "Personal & Family", "primary": "family", "subject": "family calendar"},
    {"name": "range pass renewal window", "dominant": "Golf Equipment", "primary": "golf-equipment", "subject": "golf equipment"},
    {"name": "household finance due date", "dominant": "Life Logistics", "primary": "life", "subject": "property taxes"},
    {"name": "configured watch expiration is near", "dominant": "Travel", "primary": "travel", "subject": "travel logistics"},
    {"name": "Sonar adoption remains below target", "dominant": "Work", "primary": "work", "subject": "Sonar onboarding"},
    {"name": "no spotlight after suppression", "dominant": None, "primary": None},
    {"name": "Fed path affects housing math", "dominant": "Finance & Markets", "primary": "finance", "subject": "Fed and CPI path"},
    {"name": "dryer vent task became risk", "dominant": "Home Ownership", "primary": "home", "subject": "home upkeep"},
    {"name": "project validation changed direction", "dominant": "Side Projects", "primary": "side-project", "subject": "side-project direction"},
    {"name": "quiet Sunday review", "dominant": None, "primary": None},
]

