from __future__ import annotations

from .briefing_simulator_helpers import SimulatedScenario, finance_signal, signal


SCENARIOS = [
    SimulatedScenario(
        "normal tuesday",
        "Low-signal day where a forced hero would overstate importance.",
        [],
        [
            signal(
                "Wednesday is likely your best golf window this week",
                "Forecast conditions are materially better than the rest of the week.",
                category="opportunity",
                source="weather",
                topic="Golf",
                priority=7,
                importance=76,
                actionability=48,
                story_type="focusos",
            ),
            signal(
                "Yankees won 5-0",
                "Good result, but no meaningful change to your posture today.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=5,
                importance=45,
            ),
            signal(
                "AI policy discussion stayed mostly procedural",
                "Useful context, but not a shift that should dominate the morning.",
                category="awareness",
                source="topic",
                topic="AI",
                priority=5,
                importance=48,
            ),
        ],
    ),
    SimulatedScenario(
        "boring market day",
        "Portfolio is stable; external context should not inflate the page.",
        [],
        [
            signal(
                "Markets were quiet overnight",
                "No configured portfolio or market threshold changed.",
                category="awareness",
                source="market",
                topic="Bitcoin",
                priority=4,
                importance=35,
            ),
            signal(
                "Yankees had a scheduled off day",
                "Nothing changed in the season picture.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=4,
                importance=35,
            ),
            signal(
                "Golf forecast remains playable but ordinary",
                "No day is materially better than the rest of the week.",
                category="awareness",
                source="weather",
                topic="Golf",
                priority=4,
                importance=42,
                story_type="focusos",
            ),
        ],
    ),
    SimulatedScenario(
        "market crash day",
        "Major portfolio day where a dominant hero is justified.",
        [
            finance_signal(
                "Technology allocation dropped 9.0% in one session",
                "A large move changed portfolio risk and rebalancing context.",
                importance=96,
            ),
            finance_signal(
                "MSFT crossed drawdown threshold",
                "MSFT moved from ordinary volatility into a review zone.",
                category="opportunity",
                priority=8,
                importance=88,
            ),
            finance_signal(
                "Cash reserve is below target after market move",
                "Available cash no longer covers the configured reserve target.",
                importance=90,
            ),
        ],
        [
            signal(
                "Bitcoin fell 14.0% over 24 hours",
                "Crypto moved into a review range, but it belongs inside the portfolio state.",
                category="opportunity",
                source="crypto",
                topic="Bitcoin",
                priority=8,
                importance=86,
            ),
            signal(
                "Yankees won 4-2",
                "Good result, no meaningful change to season outlook.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=4,
                importance=36,
            ),
        ],
    ),
    SimulatedScenario(
        "crypto crash day",
        "Crypto should matter only when it changes the user's portfolio posture.",
        [
            finance_signal(
                "BTC crossed drawdown threshold",
                "Bitcoin moved from background tracking into a portfolio review zone.",
                category="opportunity",
                priority=8,
                importance=86,
            ),
            finance_signal(
                "Cash remains deployable",
                "Cash is above reserve threshold during a crypto drawdown.",
                category="opportunity",
                priority=7,
                importance=79,
            ),
        ],
        [
            signal(
                "Bitcoin fell 18.0% over 24 hours",
                "The move is large enough to affect portfolio review context.",
                category="opportunity",
                source="crypto",
                topic="Bitcoin",
                priority=8,
                importance=84,
            ),
            signal(
                "AI product launches were routine",
                "No material change to the AI landscape.",
                category="awareness",
                source="topic",
                topic="AI",
                priority=4,
                importance=38,
            ),
        ],
    ),
    SimulatedScenario(
        "no news day",
        "Tests whether the layout can avoid inventing a hero.",
        [],
        [
            signal(
                "No major portfolio actions currently identified",
                "Portfolio thresholds were checked and none require attention.",
                category="awareness",
                source="portfolio",
                topic="portfolio",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
            signal(
                "Golf forecast is ordinary this week",
                "No day stands out enough to plan around.",
                category="awareness",
                source="weather",
                topic="Golf",
                priority=3,
                importance=36,
                story_type="focusos",
            ),
            signal(
                "Yankees schedule is quiet",
                "No result or injury materially changes the outlook.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=3,
                importance=34,
            ),
        ],
    ),
    SimulatedScenario(
        "golf weather week",
        "A Type B life-planning item should lead if portfolio is quiet.",
        [],
        [
            signal(
                "Thursday is likely your best golf window this month",
                "Forecast conditions are materially better than the rest of the ten-day window.",
                category="opportunity",
                source="weather",
                topic="Golf",
                priority=8,
                importance=82,
                actionability=56,
                story_type="focusos",
            ),
            signal(
                "Portfolio thresholds remain quiet",
                "No allocation or drawdown threshold changed.",
                category="awareness",
                source="portfolio",
                topic="portfolio",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
            signal(
                "AI funding news stayed incremental",
                "No major capability or access shift.",
                category="awareness",
                source="topic",
                topic="AI",
                priority=4,
                importance=40,
            ),
        ],
    ),
    SimulatedScenario(
        "yankees playoff clinch",
        "Sports can matter when it changes context, but should not feel like a task.",
        [],
        [
            signal(
                "Yankees clinched a playoff spot",
                "This changes the season context and upcoming stakes.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=8,
                importance=72,
            ),
            signal(
                "Portfolio thresholds remain quiet",
                "No portfolio review condition changed.",
                category="awareness",
                source="portfolio",
                topic="portfolio",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
            signal(
                "Weekend golf weather is playable",
                "Conditions are fine but not meaningfully better than alternatives.",
                category="awareness",
                source="weather",
                topic="Golf",
                priority=4,
                importance=42,
                story_type="focusos",
            ),
        ],
    ),
    SimulatedScenario(
        "yankees routine win",
        "Routine sports reporting should recede or be omitted.",
        [],
        [
            signal(
                "Yankees won 6-3",
                "Good result, but no meaningful change to your posture today.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=4,
                importance=36,
            ),
            signal(
                "Wednesday is likely your best golf window this week",
                "Forecast conditions are better than the rest of the week.",
                category="opportunity",
                source="weather",
                topic="Golf",
                priority=7,
                importance=76,
                story_type="focusos",
            ),
            signal(
                "AI regulation discussion stayed unresolved",
                "Worth tracking, but no new decision context.",
                category="awareness",
                source="topic",
                topic="AI",
                priority=5,
                importance=46,
            ),
        ],
    ),
    SimulatedScenario(
        "rutgers game week",
        "A personal calendar-adjacent item should outrank generic news.",
        [],
        [
            signal(
                "Rutgers game week needs a plan",
                "Kickoff, travel, and ticket timing make this a real planning item.",
                category="action",
                source="rutgers",
                topic="Rutgers",
                priority=8,
                importance=84,
                actionability=78,
                story_type="focusos",
            ),
            signal(
                "Portfolio thresholds remain quiet",
                "No portfolio state changed.",
                category="awareness",
                source="portfolio",
                topic="portfolio",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
            signal(
                "Yankees won 5-4",
                "Good result, no meaningful change to season outlook.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=4,
                importance=36,
            ),
        ],
    ),
    SimulatedScenario(
        "rutgers tickets renew friday",
        "Deadline-like personal item should be Today, but not corporate.",
        [],
        [
            signal(
                "Rutgers tickets renew Friday",
                "The window closes soon, so this belongs on your radar today.",
                category="action",
                source="rutgers",
                topic="Rutgers",
                priority=9,
                importance=88,
                actionability=86,
                story_type="focusos",
            ),
            signal(
                "Golf weather is ordinary",
                "No day is clearly better than the rest.",
                category="awareness",
                source="weather",
                topic="Golf",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
            signal(
                "AI model news was incremental",
                "No major access or capability shift.",
                category="awareness",
                source="topic",
                topic="AI",
                priority=4,
                importance=40,
            ),
        ],
    ),
]
