from __future__ import annotations

from .briefing_simulator_helpers import SimulatedScenario, finance_signal, signal


SCENARIOS = [
    SimulatedScenario(
        "vacation week",
        "Travel planning should lead when dates create risk.",
        [],
        [
            signal(
                "Vacation departure needs a travel check",
                "Weather and airport timing could affect departure planning.",
                category="action",
                source="travel",
                topic="Travel",
                priority=8,
                importance=86,
                actionability=80,
                story_type="focusos",
            ),
            signal(
                "Portfolio thresholds remain quiet",
                "No review condition changed while travel is approaching.",
                category="awareness",
                source="portfolio",
                topic="portfolio",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
            signal(
                "Yankees start a normal series",
                "No special stakes beyond the schedule.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=4,
                importance=36,
            ),
        ],
    ),
    SimulatedScenario(
        "busy work week",
        "Work context should dominate only if inactivity or deadline signals exist.",
        [],
        [
            signal(
                "Two projects have been inactive for 10 days",
                "This may create hidden drag if it is not reviewed.",
                category="action",
                source="work",
                topic="Work",
                priority=8,
                importance=84,
                actionability=78,
                story_type="focusos",
            ),
            signal(
                "Wednesday is a good golf window",
                "Good weather exists, but work context may constrain timing.",
                category="opportunity",
                source="weather",
                topic="Golf",
                priority=6,
                importance=68,
                story_type="focusos",
            ),
            signal(
                "AI policy news remains background",
                "Worth knowing, not a near-term decision.",
                category="awareness",
                source="topic",
                topic="AI",
                priority=4,
                importance=42,
            ),
        ],
    ),
    SimulatedScenario(
        "ai breakthrough day",
        "External news can lead if the signal is genuinely high.",
        [],
        [
            signal(
                "AI capability jump changes tool landscape",
                "A major model release may affect which tools are worth using this week.",
                category="awareness",
                source="topic",
                topic="AI",
                priority=9,
                importance=88,
            ),
            signal(
                "Portfolio thresholds remain quiet",
                "No portfolio review condition changed.",
                category="awareness",
                source="portfolio",
                topic="portfolio",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
            signal(
                "Golf forecast is ordinary",
                "No strong planning window emerged.",
                category="awareness",
                source="weather",
                topic="Golf",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
        ],
    ),
    SimulatedScenario(
        "iran escalation day",
        "World news should be Background unless it changes practical posture.",
        [],
        [
            signal(
                "Iran escalation raises oil and travel risk",
                "The situation may affect markets and travel planning, but no personal action is implied yet.",
                category="awareness",
                source="topic",
                topic="Iran",
                priority=8,
                importance=76,
            ),
            signal(
                "Portfolio thresholds remain quiet",
                "No portfolio review condition changed.",
                category="awareness",
                source="portfolio",
                topic="portfolio",
                priority=3,
                importance=34,
                story_type="focusos",
            ),
            signal(
                "Yankees won 2-1",
                "Good result, no meaningful change to season outlook.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=4,
                importance=36,
            ),
        ],
    ),
    SimulatedScenario(
        "major event day",
        "Single external event may justify one dominant story.",
        [],
        [
            signal(
                "Major market closure disrupts normal trading",
                "This changes how portfolio signals should be interpreted today.",
                category="action",
                source="market",
                topic="Markets",
                priority=10,
                importance=98,
                actionability=88,
            ),
            signal(
                "Travel advisory issued for vacation route",
                "The advisory could affect departure timing.",
                category="action",
                source="travel",
                topic="Travel",
                priority=8,
                importance=86,
                actionability=78,
                story_type="focusos",
            ),
            signal(
                "Yankees game postponed",
                "Schedule changed, but no broader season impact.",
                category="awareness",
                source="topic",
                topic="Yankees",
                priority=4,
                importance=36,
            ),
        ],
    ),
    SimulatedScenario(
        "liquidity warning day",
        "Liquid cash below target should become Needs attention.",
        [
            finance_signal(
                "Liquid cash is below the $10,000 target",
                "Available liquid cash is close enough to the configured target to change spending and runway posture.",
                importance=92,
            ),
        ],
        [
            signal(
                "Opinion-only market chatter stayed noisy",
                "No verified price or thesis change was attached to the chatter.",
                category="awareness",
                source="market",
                topic="Markets",
                priority=3,
                importance=30,
            ),
        ],
    ),
    SimulatedScenario(
        "github action queue day",
        "Public repo health should create a practical action queue.",
        [],
        [
            signal(
                "focus-os has an automated PR",
                "An automated PR is open and likely quick to review.",
                category="action",
                source="github",
                topic="github",
                priority=8,
                importance=84,
                actionability=74,
                story_type="focusos",
            ),
            signal(
                "Archived repo emitted noise",
                "Archived repositories are explicitly suppressed.",
                category="awareness",
                source="github",
                topic="github",
                priority=2,
                importance=20,
            ),
        ],
    ),
    SimulatedScenario(
        "shopping media quiet day",
        "Shopping and media should remain optional unless tied to saved interests.",
        [],
        [
            signal(
                "Generic sale stayed quiet",
                "No saved product or target price matched the deal.",
                category="awareness",
                source="shopping",
                topic="Shopping",
                priority=2,
                importance=24,
            ),
            signal(
                "High-confidence media match is available",
                "A short recommendation matches known preferences and current availability.",
                category="awareness",
                source="media",
                topic="Media",
                priority=5,
                importance=58,
            ),
        ],
    ),
    SimulatedScenario(
        "life reminder action day",
        "User-entered personal admin should surface when the warning window opens.",
        [],
        [
            signal(
                "Bogey medication refill enters warning window",
                "The user-entered refill date is close enough to avoid a scramble.",
                category="action",
                source="watchlist",
                topic="Life",
                priority=9,
                importance=90,
                actionability=84,
                story_type="focusos",
            ),
            signal(
                "Undated note stayed quiet",
                "The note has no action window or posture change.",
                category="awareness",
                source="watchlist",
                topic="Life",
                priority=2,
                importance=22,
                story_type="focusos",
            ),
        ],
    ),
]
