from __future__ import annotations


GLOBAL_GUARDRAILS = [
    "Prefer silence over filler.",
    "Do not surface generic summaries.",
    "Do not surface unchanged facts.",
    "Do not surface content unless it changes a decision, posture, plan, risk, or saved interest.",
    "Collapse repeated related signals into one grouped item.",
    "Separate user-provided facts from externally checked facts.",
    "Separate checked facts from inferred conclusions.",
    "If a watch is quiet, explain why briefly.",
    "Do not let sports, shopping, or media dominate unless the event is genuinely material.",
]


KNOWN_MISSING_SOURCE_STATUSES = [
    {
        "name": "Direct Fidelity",
        "status": "missing",
        "message": "Direct Fidelity integration is unavailable; use manual portfolio CSV.",
        "details": {"account": "Fidelity", "fallback": "manual_portfolio_csv"},
    },
    {
        "name": "Direct SoFi",
        "status": "missing",
        "message": "Direct SoFi integration is unavailable; use manual inputs or CSV-backed portfolio state.",
        "details": {"account": "SoFi", "fallback": "manual_portfolio_csv"},
    },
    {
        "name": "Direct Tastytrade",
        "status": "missing",
        "message": "Direct Tastytrade integration is unavailable; use manual portfolio CSV.",
        "details": {"account": "Tastytrade", "fallback": "manual_portfolio_csv"},
    },
    {
        "name": "BTC cost basis",
        "status": "manual_needed",
        "message": "BTC cost basis is manual unless a brokerage or crypto account adapter is connected.",
        "details": {"asset": "BTC", "fallback": "manual_crypto_notes"},
    },
    {
        "name": "Amazon account",
        "status": "manual_needed",
        "message": "Amazon purchase and preference data is unavailable; shopping watches use manual interests.",
        "details": {"account": "Amazon", "fallback": "manual_shopping_interests"},
    },
    {
        "name": "Netflix watchlist",
        "status": "manual_needed",
        "message": "Netflix direct watchlist data is unavailable; media watches use manual preferences.",
        "details": {"account": "Netflix", "fallback": "manual_media_preferences"},
    },
    {
        "name": "Prime Video watchlist",
        "status": "manual_needed",
        "message": "Prime Video direct watchlist data is unavailable; media watches use manual preferences.",
        "details": {"account": "Prime Video", "fallback": "manual_media_preferences"},
    },
    {
        "name": "YouTube",
        "status": "requires_configuration",
        "message": "YouTube is available only if an API integration is configured.",
        "details": {"account": "YouTube", "fallback": "manual_media_preferences"},
    },
]


SOURCE_REGISTRY = [
    {
        "source_id": "manual_notes",
        "label": "Manual notes",
        "source_type": "manual_input",
        "auth_required": False,
        "enabled_by_default": True,
        "available": True,
        "current_access_method": "local watch notes",
        "supported_entities": ["life notes", "project notes", "manual reminders"],
        "used_for": ["Life notes, reminders, and personal admin"],
    },
    {
        "source_id": "manual_portfolio_csv",
        "label": "Manual portfolio CSV",
        "source_type": "manual_input",
        "auth_required": False,
        "enabled_by_default": True,
        "available": True,
        "current_access_method": "CSV upload",
        "supported_entities": ["Fidelity", "SoFi", "Tastytrade"],
        "used_for": ["Personal finance and liquidity runway"],
    },
    {
        "source_id": "market_price_adapter",
        "label": "Market price adapter",
        "source_type": "market_data",
        "auth_required": False,
        "enabled_by_default": True,
        "available": True,
        "current_access_method": "Yahoo Finance chart endpoint",
        "supported_entities": ["UNH", "USO", "SPY", "QQQ", "AAPL", "S&P 500 proxy"],
        "used_for": ["Investing ideas and market pullbacks"],
    },
    {
        "source_id": "CoinGecko",
        "label": "CoinGecko",
        "source_type": "crypto_data",
        "auth_required": False,
        "enabled_by_default": True,
        "available": True,
        "current_access_method": "CoinGecko simple price API",
        "supported_entities": ["BTC"],
        "used_for": ["Bitcoin accumulation posture"],
    },
    {
        "source_id": "GitHub API",
        "label": "GitHub API",
        "source_type": "repo_data",
        "auth_required": False,
        "enabled_by_default": True,
        "available": True,
        "current_access_method": "public REST API",
        "supported_entities": ["dock108dev public repos"],
        "used_for": ["Personal GitHub repo health", "Side project and FocusOS validation"],
    },
    {
        "source_id": "Open-Meteo",
        "label": "Open-Meteo",
        "source_type": "weather_data",
        "auth_required": False,
        "enabled_by_default": True,
        "available": True,
        "current_access_method": "Open-Meteo forecast API",
        "supported_entities": ["Basking Ridge, NJ"],
        "used_for": ["Golf weather for Basking Ridge"],
    },
    {
        "source_id": "official_changelog_feed",
        "label": "RSS / official changelog feed adapter",
        "source_type": "news_or_changelog",
        "auth_required": False,
        "enabled_by_default": True,
        "available": False,
        "current_access_method": "registry placeholder",
        "supported_entities": ["OpenAI", "Anthropic", "GitHub", "Apple", "Microsoft"],
        "used_for": ["Big tech, AI, and major company releases"],
    },
    {
        "source_id": "sports_feed_adapter",
        "label": "Sports feed adapter",
        "source_type": "sports_data",
        "auth_required": False,
        "enabled_by_default": True,
        "available": False,
        "current_access_method": "registry placeholder",
        "supported_entities": ["Rutgers", "Yankees", "Cowboys", "F1", "PGA"],
        "used_for": ["Sports radar with spoiler-safe recap"],
    },
    {
        "source_id": "Plaid",
        "label": "Plaid",
        "source_type": "personal_account",
        "auth_required": True,
        "enabled_by_default": False,
        "available": False,
        "current_access_method": "missing auth",
        "supported_entities": ["bank accounts", "brokerage accounts"],
        "used_for": ["Personal finance and liquidity runway"],
    },
    {
        "source_id": "Steam API",
        "label": "Steam API",
        "source_type": "shopping_data",
        "auth_required": False,
        "enabled_by_default": False,
        "available": False,
        "current_access_method": "not wired",
        "supported_entities": ["games", "wishlists if configured"],
        "used_for": ["Shopping and product interest radar"],
    },
    {
        "source_id": "TMDB",
        "label": "TMDB",
        "source_type": "media_data",
        "auth_required": True,
        "enabled_by_default": False,
        "available": False,
        "current_access_method": "missing auth",
        "supported_entities": ["movies", "TV"],
        "used_for": ["Media and watchlist radar"],
    },
]


PERSONAL_ACCOUNT_REGISTRY = {
    "finance_accounts": [
        {
            "name": "Fidelity",
            "type": "brokerage",
            "desired_access": "direct_if_possible",
            "mvp_access": "manual_csv_or_available_adapter",
        },
        {
            "name": "SoFi",
            "type": "bank_or_brokerage",
            "desired_access": "direct_if_possible",
            "mvp_access": "manual_or_available_adapter",
        },
        {
            "name": "Tastytrade",
            "type": "brokerage",
            "desired_access": "direct_if_possible",
            "mvp_access": "manual_or_available_adapter",
        },
    ],
    "github": {
        "owner": "dock108dev",
        "scope": "public_repos_only",
        "ignore_archived": True,
    },
    "sports": {
        "teams": ["Rutgers football", "Rutgers basketball", "Yankees", "Cowboys"],
        "events": [
            "NFL playoffs",
            "MLB playoffs",
            "NBA playoffs",
            "NHL playoffs",
            "March Madness",
            "College Football Playoff",
            "World Cup",
            "Olympics",
            "Champions League",
            "major global sports events",
            "F1",
            "PGA Tour",
            "golf majors",
        ],
    },
    "golf_weather": {
        "location": "Basking Ridge, NJ",
        "closed_day": "Monday",
        "friday_afternoon_note": "likely crowded",
    },
    "shopping": {
        "categories": [
            "tech",
            "video games",
            "gaming PC",
            "graphics cards",
            "monitors",
            "software subscriptions",
            "major console news",
        ],
    },
    "media": {
        "services": ["YouTube", "YouTube TV", "Netflix", "Prime Video"],
    },
}
