from __future__ import annotations

DEFAULT_SURFACE_WHEN = [
    "risk changed materially",
    "decision deadline is near",
    "summary would save user effort",
]
DEFAULT_SUPPRESS_WHEN = [
    "generic reminders",
    "unchanged source data",
    "filler that only says the watched object is coming up",
]
DEFAULT_WATCH_FOR = ["timing", "schedule changes"]
WATCH_KINDS = {"personal_tracker", "external_monitor", "hybrid"}
WATCH_PRIORITIES = {"primary_allowed", "watch_only", "quiet_by_default"}
PERSONAL_SOURCE_LABELS = {
    "manual portfolio imports",
    "calendar",
    "work project status",
    "work project metrics",
    "repo migration tracker",
    "project notes",
    "project spend tracker",
    "project activity log",
    "project roadmap",
    "contractor messages",
    "home maintenance log",
    "vet or pharmacy source",
    "pet supply source",
    "boarding reservation source",
    "care calendar",
    "calendar and admin inbox",
    "admin inbox",
    "bill calendar",
    "hotel reservation source",
}
EXTERNAL_SOURCE_LABELS = {
    "weather",
    "parking feed",
    "maps or transit",
    "calendar or venue/source update",
    "post-event sources",
    "developer docs",
    "vendor pricing pages",
    "vendor changelog",
    "crypto price feed",
    "rate feed",
    "market price feed",
    "sports results feed",
    "sports schedule feed",
    "sports injury reports",
    "sports standings feed",
    "sports rankings feed",
    "golf retailer and manufacturer feeds",
    "golf fitting calendar",
    "retailer price feed",
    "manufacturer release calendar",
    "airline source",
    "airline and maps",
}
PORTFOLIO_THRESHOLDS = {
    "cash_above": 0.08,
    "technology_above": 0.45,
    "single_position_above": 0.25,
    "pullback_above": 0.05,
}
SOURCE_HINTS = {
    "weather": "weather",
    "wind": "weather",
    "rain": "weather",
    "tee time": "calendar",
    "parking": "parking feed",
    "traffic": "maps or transit",
    "timing": "calendar",
    "schedule changes": "calendar or venue/source update",
    "summary": "post-event sources",
    "developer tooling": "developer docs",
    "api": "developer docs",
    "pricing": "vendor pricing pages",
    "xcode": "developer docs",
    "ai": "vendor changelog",
    "cash": "manual portfolio imports",
    "concentration": "manual portfolio imports",
    "pullbacks": "manual portfolio imports",
    "Bitcoin": "crypto price feed",
    "mortgage rates": "rate feed",
    "market moves": "market price feed",
    "results": "sports results feed",
    "next game": "sports schedule feed",
    "injuries": "sports injury reports",
    "standings": "sports standings feed",
    "rankings": "sports rankings feed",
    "equipment": "golf retailer and manufacturer feeds",
    "fitting": "golf fitting calendar",
    "price changes": "retailer price feed",
    "release windows": "manufacturer release calendar",
    "blocked teams": "work project status",
    "adoption gaps": "work project metrics",
    "migration status": "repo migration tracker",
    "deadline": "calendar",
    "validation": "project notes",
    "cost": "project spend tracker",
    "progress stalls": "project activity log",
    "launch windows": "project roadmap",
    "due dates": "calendar",
    "contractor timing": "contractor messages",
    "maintenance risk": "home maintenance log",
    "appointments": "calendar",
    "food": "pet supply source",
    "boarding": "boarding reservation source",
    "medication": "vet or pharmacy source",
    "coverage": "care calendar",
    "renewals": "calendar and admin inbox",
    "paperwork": "admin inbox",
    "deadlines": "calendar",
    "family dates": "calendar",
    "bills": "bill calendar",
    "flights": "airline source",
    "hotels": "hotel reservation source",
    "airport timing": "airline and maps",
}
WATCH_KEYWORDS = {
    "weather": {"weather", "rain", "temperature", "forecast"},
    "parking": {"parking", "drive"},
    "traffic": {"traffic", "transit", "train", "airport", "flight"},
    "timing": {"time", "timing", "door", "doors", "starts", "keynote", "kickoff"},
    "schedule changes": {"schedule", "changes", "delay", "postponed", "policy"},
    "summary": {"summarize", "summary", "announcements", "takeaways", "recap"},
    "developer tooling": {"xcode", "developer", "tooling", "api", "sdk"},
    "ai": {"ai", "siri", "model"},
    "cash": {"cash"},
    "concentration": {"concentration", "allocation"},
    "pullbacks": {"pullback", "pullbacks", "drawdown"},
    "Bitcoin": {"bitcoin", "btc"},
    "mortgage rates": {"mortgage", "rates"},
    "market moves": {"market", "markets"},
    "results": {"results", "result", "won", "lost"},
    "next game": {"next", "game", "kickoff"},
    "injuries": {"injury", "injuries"},
    "standings": {"standings", "division"},
    "rankings": {"rankings", "ranking"},
    "equipment": {"equipment", "gear", "club", "clubs"},
    "fitting": {"fitting", "fit"},
    "price changes": {"price", "prices"},
    "release windows": {"release", "releases"},
    "blocked teams": {"blocked", "team", "teams"},
    "adoption gaps": {"adoption", "gaps"},
    "migration status": {"migration", "repo", "namespace"},
    "deadline": {"deadline", "deadlines"},
    "validation": {"validation", "validate"},
    "cost": {"cost", "costs"},
    "progress stalls": {"stalls", "stalled", "progress"},
    "launch windows": {"launch"},
    "due dates": {"due"},
    "contractor timing": {"contractor"},
    "maintenance risk": {"maintenance"},
    "appointments": {"appointment", "appointments"},
    "food": {"food"},
    "boarding": {"boarding"},
    "medication": {"medication", "medicine"},
    "coverage": {"coverage"},
    "renewals": {"renewal", "renewals"},
    "paperwork": {"paperwork"},
    "family dates": {"family"},
    "bills": {"bill", "bills"},
    "flights": {"flight", "flights"},
    "hotels": {"hotel", "hotels"},
    "airport timing": {"airport"},
}
WEEKDAYS = {
    "monday": 0,
    "tuesday": 1,
    "wednesday": 2,
    "thursday": 3,
    "friday": 4,
    "saturday": 5,
    "sunday": 6,
}
